import dotenv from "dotenv"; 
dotenv.config();
import {assert} from "./common";
import {main as deploy} from "./deploy";
import {main as upgradeRebalancer} from "./upgradeRebalancer";
import {main as upgradeRepayer} from "./upgradeRepayer";
import {main as redeployStash} from "./redeployStash";
import {main as deployCensoredMulticall} from "./deployCensoredMulticall";
import {main as deployPool} from "./deployPool";
import {main as deployStablecoinPool} from "./deployStablecoinPool";
import {main as deployRepayer} from "./deployRepayer";
import {main as upgradeLiquidityHub} from "./upgradeLiquidityHub";
import {main as deployPoolAave} from "./deployPoolAave";
import {main as deployPoolAaveLongTerm} from "./deployPoolAaveLongTerm";
import {main as deployStandaloneRepayer} from "./deployStandaloneRepayer";
import {main as deployPublicPool} from "./deployPublicPool";
import {main as deployERC4626Adapter} from "./deployERC4626Adapter";
import {main as deployTokenProcessor} from "./deployTokenProcessor";
import {main as upgradeTokenProcessor} from "./upgradeTokenProcessor";
import {main as deployPaxosOracle} from "./deployPaxosOracle";
import {main as deployStashDex} from "./deployStashDex";
import {main as deployStashDexProcessor} from "./deployStashDexProcessor";
import {main as upgradeStashDexProcessor} from "./upgradeStashDexProcessor";
import {main as upgradeStashDex} from "./upgradeStashDex";
import {main as deployNetter} from "./deployNetter";

async function main() {
  console.log("Test deploy.");
  await deploy();
  console.log("Test upgradeRebalancer.");
  await upgradeRebalancer();
  console.log("Test upgradeRepayer.");
  await upgradeRepayer();
  console.log("Test redeployStash.");
  await redeployStash();
  console.log("Test deployPool.");
  await deployPool();
  console.log("Test deployStablecoinPool.");
  await deployStablecoinPool();
  console.log("Test upgradeLiquidityHub.");
  await upgradeLiquidityHub();
  console.log("Test deployPoolAave.");
  await deployPoolAave();
  console.log("Test deployPoolAaveLongTerm.");
  await deployPoolAaveLongTerm();
  console.log("Test deployPublicPool.");
  await deployPublicPool();
  console.log("Test deployERC4626Adapter.");
  await deployERC4626Adapter();
  console.log("Test deployRepayer.");
  await deployRepayer();
  process.env.PROCESSOR_TOKEN = "USDC";
  console.log("Test deployTokenProcessor.");
  await deployTokenProcessor();
  console.log("Test upgradeTokenProcessor.");
  await upgradeTokenProcessor();
  console.log("Test deployPaxosOracle.");
  await deployPaxosOracle();
  console.log("Test deployStashDexProcessor USDC.");
  await deployStashDexProcessor();
  console.log("Test deployStashDex.");
  await deployStashDex();
  console.log("Test upgradeStashDexProcessor USDC.");
  await upgradeStashDexProcessor();
  console.log("Test upgradeStashDex.");
  await upgradeStashDex();
  console.log("Test deployNetter.");
  await deployNetter();
  console.log("Test deployStandaloneRepayer.");
  process.env.STANDALONE_REPAYER_ENV = "SparkStage";
  await deployStandaloneRepayer();
  console.log("Test deployCensoredMulticall.");
  process.env.DEPLOY_ID = "NEW_ID";
  await deployCensoredMulticall();
  console.log("Success.");
}

assert(process.env.SCRIPT_ENV === "CI", "Unexpected SCRIPT_ENV value");
main();
