name: Echidna

on:
  pull_request:
    branches:
      - main

jobs:
  echidna:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Echidna for EchidnaPublicLiquidityPool
        uses: crytic/echidna-action@f7e374e42bf7131f7307a92f5549ed6b2fd17c9d # v2.0.2
        with:
          solc-version: 0.8.28
          files: .
          contract: EchidnaPublicLiquidityPool
          config: contracts/echidna/config.yaml

      - name: Run Echidna for EchidnaLiquidityHub
        uses: crytic/echidna-action@f7e374e42bf7131f7307a92f5549ed6b2fd17c9d # v2.0.2
        with:
          solc-version: 0.8.28
          files: .
          contract: EchidnaLiquidityHub
          config: contracts/echidna/config.yaml

      - name: Run Echidna for EchidnaLiquidityMining
        uses: crytic/echidna-action@f7e374e42bf7131f7307a92f5549ed6b2fd17c9d # v2.0.2
        with:
          solc-version: 0.8.28
          files: .
          contract: EchidnaLiquidityMining
          config: contracts/echidna/config.yaml

      - name: Run Echidna for EchidnaLiquidityPool
        uses: crytic/echidna-action@f7e374e42bf7131f7307a92f5549ed6b2fd17c9d # v2.0.2
        with:
          solc-version: 0.8.28
          files: .
          contract: EchidnaLiquidityPool
          config: contracts/echidna/config.yaml
